#!/bin/bash

#SBATCH --time=1:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=30   # 30 processor core(s) per node


cd data


#Fetch fasta,fasta index, and gtf for Human GRCh38.
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf.gz
gunzip GCA_000001405.15*
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.fai

#Remove "chr" from chr# in fasta,fasta index, and gtf.
sed -i s'/chr//g' GCA_000001405.15*
#Create sequence dictionary of fasta
gatk CreateSequenceDictionary -R GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna

# Generate STAR genome
STAR --runMode genomeGenerate --genomeDir star_index_Human --sjdbGTFfile GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf --genomeFastaFiles GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna --runThreadN 30

