#!/bin/bash

#SBATCH --time=1:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=30   # 30 processor core(s) per node


cd data


#Fetch fasta and gtf for Human GRCh38.
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf.gz
gunzip GCA_000001405.15*


#Create sequence dictionary of fasta
gatk CreateSequenceDictionary -R GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna
#Create fasta index
samtools faidx GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna

# Generate STAR genome
STAR --runMode genomeGenerate --genomeDir star_index_Human --sjdbGTFfile GCA_000001405.15_GRCh38_full_analysis_set.refseq_annotation.gtf --genomeFastaFiles GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna --runThreadN 30


# #The ClinVar database (https://www.ncbi.nlm.nih.gov/clinvar/) contains information on the medical relevance of genetic variations(Landrum et al. 2018).   
# #Get GRCh38 VCFs  
wget https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz
wget https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz.tbi
# #Get variant summary file and remove GRCh37 data fromn it. 
wget https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
gunzip variant_summary.txt.gz
cat variant_summary.txt | grep -v "GRCh37" > ClinVarSummaryGRCh38.txt
rm variant_summary.txt

#Get Gnomad germline-resource for GATK
wget -m ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/Mutect2
mv ftp.broadinstitute.org/bundle/Mutect2/af-only-gnomad.hg38.vcf.gz .
