#!/bin/bash

#SBATCH --time=10:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=30   # 30 processor core(s) per node
#SBATCH -p RM-shared


#Loop through run accessiom ids and get total num of SNPs for each id. 
cat RAids.txt  | while read i;do
        gunzip -c output/$i/All.$i.vcf.gz | grep -v "#" | wc -l >> SNPS
done


paste RAids.txt SNPS > AllRunsSNPS.txt
